/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/jobs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Create Job */
        readonly post: operations["create_job"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/jobs/{job_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Job */
        readonly get: operations["get_job"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/platform": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Platform */
        readonly get: operations["platform_api_v1_platform_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/worker/leases/claim": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Claim */
        readonly post: operations["claim_lease"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/worker/leases/finish": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Finish */
        readonly post: operations["finish_lease"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/worker/leases/renew": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Renew */
        readonly post: operations["renew_lease"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health/live": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Live */
        readonly get: operations["live_health_live_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Ready */
        readonly get: operations["ready_health_ready_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        readonly ApiError: {
            readonly code: components["schemas"]["ErrorCode"];
            /** Message */
            readonly message: string;
        };
        /** ClaimRequest */
        readonly ClaimRequest: {
            /**
             * Lease Seconds
             * @default 60
             */
            readonly lease_seconds: number;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        readonly ErrorCode: "UNAUTHORIZED" | "FORBIDDEN" | "WRITES_DISABLED" | "NOT_FOUND" | "LEASE_REJECTED" | "CONFLICT" | "INVALID_REQUEST" | "DATABASE_UNAVAILABLE";
        /** ExecutionSnapshot */
        readonly ExecutionSnapshot: {
            readonly agent: components["schemas"]["RevisionRef"];
            /**
             * Max Executions
             * @default 3
             */
            readonly max_executions: number;
            readonly model: components["schemas"]["RevisionRef"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            readonly schema_version: "1";
            readonly task: components["schemas"]["RevisionRef"];
            /**
             * Timeout Sec
             * @default 300
             */
            readonly timeout_sec: number;
        };
        /**
         * FailureReason
         * @enum {string}
         */
        readonly FailureReason: "AGENT_ERROR" | "VERIFIER_ERROR" | "INFRA_ERROR" | "UNVERIFIED";
        /** FinishRequest */
        readonly FinishRequest: {
            readonly lease: components["schemas"]["LeaseReference"];
            readonly result: components["schemas"]["ResultCommit"];
        };
        /** HealthResponse */
        readonly HealthResponse: {
            /** Service */
            readonly service: string;
            /** Status */
            readonly status: string;
            /** Version */
            readonly version: string;
        };
        /** JobCreateRequest */
        readonly JobCreateRequest: {
            /**
             * Job Id
             * Format: uuid
             */
            readonly job_id: string;
            readonly snapshot: components["schemas"]["ExecutionSnapshot"];
        };
        /** JobView */
        readonly JobView: {
            /**
             * Job Id
             * Format: uuid
             */
            readonly job_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            readonly owner_id: string;
            readonly snapshot: components["schemas"]["ExecutionSnapshot"];
            readonly trial: components["schemas"]["TrialView"];
        };
        /** Lease */
        readonly Lease: {
            /**
             * Execution Id
             * Format: uuid
             */
            readonly execution_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            readonly expires_at: string;
            /** Fencing Token */
            readonly fencing_token: number;
            readonly snapshot: components["schemas"]["ExecutionSnapshot"];
            /**
             * Trial Id
             * Format: uuid
             */
            readonly trial_id: string;
            /**
             * Worker Id
             * Format: uuid
             */
            readonly worker_id: string;
        };
        /** LeaseReference */
        readonly LeaseReference: {
            /**
             * Execution Id
             * Format: uuid
             */
            readonly execution_id: string;
            /** Fencing Token */
            readonly fencing_token: number;
            /**
             * Trial Id
             * Format: uuid
             */
            readonly trial_id: string;
        };
        /** RenewRequest */
        readonly RenewRequest: {
            readonly lease: components["schemas"]["LeaseReference"];
            /**
             * Lease Seconds
             * @default 60
             */
            readonly lease_seconds: number;
        };
        /** ResultCommit */
        readonly ResultCommit: {
            readonly failure_reason?: components["schemas"]["FailureReason"] | null;
            /** Manifest Digest */
            readonly manifest_digest: string;
            /** Manifest Key */
            readonly manifest_key: string;
            readonly outcome: components["schemas"]["ResultOutcome"];
            /** Rewards */
            readonly rewards?: {
                readonly [key: string]: number;
            } | null;
        };
        /**
         * ResultOutcome
         * @enum {string}
         */
        readonly ResultOutcome: "SCORED" | "RUNTIME_FAILED" | "UNVERIFIED";
        /** RevisionRef */
        readonly RevisionRef: {
            /** Digest */
            readonly digest: string;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Revision */
            readonly revision: number;
        };
        /**
         * TrialStatus
         * @enum {string}
         */
        readonly TrialStatus: "PENDING" | "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED";
        /** TrialView */
        readonly TrialView: {
            /**
             * Attempt Index
             * @default 0
             * @constant
             */
            readonly attempt_index: 0;
            /** Fencing Token */
            readonly fencing_token: number;
            /**
             * Job Id
             * Format: uuid
             */
            readonly job_id: string;
            readonly result?: components["schemas"]["ResultCommit"] | null;
            readonly status: components["schemas"]["TrialStatus"];
            /**
             * Trial Id
             * Format: uuid
             */
            readonly trial_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly create_job: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    readonly get_job: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly job_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    readonly platform_api_v1_platform_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
        };
    };
    readonly claim_lease: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ClaimRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Lease"];
                };
            };
            /** @description 没有可领取的 Trial */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    readonly finish_lease: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["FinishRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TrialView"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    readonly renew_lease: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["RenewRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Lease"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    readonly live_health_live_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readonly ready_health_ready_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
        };
    };
}
